export { computeScore } from './compute-score'
export { computeMatchResult } from './compute-match'
export type { CandidateWithAssessments } from './compute-match'
export type { ScoringInputs, RoleWeights, CompositeScore } from './types'
export { scoreCandidate, matchCandidateToRequisitions } from './match'
export type { MatchCandidateInput, MatchRequisitionInput, CampaignMatchResult } from './match'
